version: '3'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"